"""
Django settings for fwupapp project.

Generated by 'django-admin startproject' using Django 5.1.1.
"""

import os
import logging
from pathlib import Path
from rest_framework.permissions import AllowAny
from azure.monitor.opentelemetry import configure_azure_monitor

# Use Azure Monitor exporters instead of OTLP


# Build paths
BASE_DIR = Path(__file__).resolve().parent.parent

# Security settings
SECRET_KEY = 'django-insecure-n4_vxq81x8+qvng6t)p)jhv1898@r_51nr5&!0e72@438%50&7'
#APPINSIGHTS_CONNECTION_STRING = os.getenv("APPINSIGHTS_CONNECTION_STRING")
DEBUG = True
ALLOWED_HOSTS = ["localhost", "127.0.0.1", "74.241.132.76","firmware-fwupapp-1","linkfirmware.duckdns.org"]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'FWapp',
    'django_auth_adfs',
    'rest_framework',
    'django_extensions',
    'corsheaders',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fwupapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fwupapp.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': 'root',
        'HOST': 'my-postgres',
        'PORT': '5432',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

DATA_UPLOAD_MAX_MEMORY_SIZE = 1073741824  # 1GB
FILE_UPLOAD_MAX_MEMORY_SIZE = 1073741824  # 1GB

# Static and media files
STATIC_URL = 'static/'
AZURE_ACCOUNT_NAME = os.getenv("AZURE_ACCOUNT_NAME")
AZURE_ACCOUNT_KEY = os.getenv("AZURE_ACCOUNT_KEY")
AZURE_MEDIA_CONTAINER = os.getenv("AZURE_MEDIA_CONTAINER")
AZURE_STATIC_CONTAINER = os.getenv("AZURE_STATIC_CONTAINER")
DEFAULT_FILE_STORAGE = 'storages.backends.azure_storage.AzureStorage'
AZURE_CUSTOM_DOMAIN = f"{AZURE_ACCOUNT_NAME}.blob.core.windows.net"
MEDIA_URL = f"{AZURE_CUSTOM_DOMAIN}/{AZURE_MEDIA_CONTAINER}/"
STATIC_URL = f"{AZURE_CUSTOM_DOMAIN}/{AZURE_STATIC_CONTAINER}/"

# Django REST Framework
CORS_ALLOWED_ORIGINS = ["http://localhost:3000", "http://127.0.0.1:3000","https://74.241.132.76","https://74.241.132.76:3000","https://linkfirmware.duckdns.org","https://linkfirmware.duckdns.org:3000"]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = ['authorization', 'content-type']
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'django_auth_adfs.rest_framework.AdfsAccessTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.AllowAny',),
}

# Django ADFS
AUTH_ADFS = {
    'CLIENT_ID': "c0b855d9-d4ce-4d41-a3e3-b998b4113ca6",
    'TENANT_ID': "0d7f219a-ad11-4fbf-b91b-8d223731a2a7",
    'AUDIENCE': "api://c0b855d9-d4ce-4d41-a3e3-b998b4113ca6",
    'ISSUER': "https://sts.windows.net/0d7f219a-ad11-4fbf-b91b-8d223731a2a7/",
    'USERNAME_CLAIM': 'email',  # Use email claim for username
    'CLAIM_MAPPING': {
        'first_name': 'name',
        'last_name': '',
        'email': 'email',
    },
    'GROUPS_CLAIM': 'roles',  # Change to 'groups' if needed
    'MIRROR_GROUPS': False,   # Set to False if roles are not used
    'RELYING_PARTY_ID': "api://c0b855d9-d4ce-4d41-a3e3-b998b4113ca6",
    'VERSION': '1.0',
}

AUTHENTICATION_BACKENDS = [
    'django_auth_adfs.backend.AdfsAccessTokenBackend',
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_URL = "django_auth_adfs:login"
LOGIN_REDIRECT_URL = '/'



# Configure Azure Monitor with your connection strin

if os.getenv('APPINSIGHTS_CONNECTION_STRING'):
    configure_azure_monitor(
        connection_string=os.getenv('APPINSIGHTS_CONNECTION_STRING'),
        enable_live_metrics=True,
    )
else:
    print("APPLICATIONINSIGHTS_CONNECTION_STRING not set. Skipping OpenTelemetry configuration.")