# Generated by Django 5.1.1 on 2024-10-15 17:00

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('FWapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firmwarepackage',
            old_name='fw_package',
            new_name='fw_package_url',
        ),
        migrations.AlterField(
            model_name='firmwarepackage',
            name='fw_package_url',
            field=models.URLField(),
        ),
    ]

# # Generated by Django 5.1.1 on 2024-10-15 17:00

# import FWapp.models
# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('FWapp', '0001_initial'),
#     ]

#     operations = [
#         migrations.AlterField(
#             model_name='firmwarepackage',
#             name='fw_package',
#             field=models.URLField(),
#         ),
#     ]
